name: Manual Nmap Scan on IP:Port List

on:
  workflow_dispatch:
   

jobs:
  nmap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Install Nmap
      run: sudo apt-get update && sudo apt-get install -y nmap

    - name: Split Live Hosts
      run: |
        awk '{ print > sprintf("hosts_part_%02d.txt", ((NR-1) % 6) + 1) }' live_hosts.txt
        rm -f nmap_scan_1.txt
        
    - name: Run Nmap scan script on file-1
      run: |
        chmod +x scan_ips_ports.sh
        ./scan_ips_ports.sh hosts_part_01.txt 1

            
    - name: Upload Nmap scan results
      uses: actions/upload-artifact@v4
      with:
        name: nmap_scan_results_1
        path: nmap_scan_1.txt

  nmap_scan_2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Install Nmap
      run: sudo apt-get update && sudo apt-get install -y nmap

    - name: Split Live Hosts
      run: |
        awk '{ print > sprintf("hosts_part_%02d.txt", ((NR-1) % 6) + 1) }' live_hosts.txt
        rm -f nmap_scan_2.txt
        
    - name: Run Nmap scan script on file-2
      run: |
        chmod +x scan_ips_ports.sh
        ./scan_ips_ports.sh hosts_part_02.txt 2

            
    - name: Upload Nmap scan results
      uses: actions/upload-artifact@v4
      with:
        name: nmap_scan_results
        path: nmap_scan_2.txt


  nmap_scan_3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Install Nmap
      run: sudo apt-get update && sudo apt-get install -y nmap

    - name: Split Live Hosts
      run: |
        awk '{ print > sprintf("hosts_part_%02d.txt", ((NR-1) % 6) + 1) }' live_hosts.txt
        rm -f nmap_scan_3.txt
        
    - name: Run Nmap scan script on file-3
      run: |
        chmod +x scan_ips_ports.sh
        ./scan_ips_ports.sh hosts_part_03.txt 3

            
    - name: Upload Nmap scan results
      uses: actions/upload-artifact@v4
      with:
        name: nmap_scan_results
        path: nmap_scan_3.txt

  nmap_scan_4:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Install Nmap
      run: sudo apt-get update && sudo apt-get install -y nmap

    - name: Split Live Hosts
      run: |
        awk '{ print > sprintf("hosts_part_%02d.txt", ((NR-1) % 6) + 1) }' live_hosts.txt
        rm -f nmap_scan_4.txt
        
    - name: Run Nmap scan script on file-4
      run: |
        chmod +x scan_ips_ports.sh
        ./scan_ips_ports.sh hosts_part_04.txt 4

            
    - name: Upload Nmap scan results
      uses: actions/upload-artifact@v4
      with:
        name: nmap_scan_results
        path: nmap_scan_4.txt

  nmap_scan_5:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Install Nmap
      run: sudo apt-get update && sudo apt-get install -y nmap

    - name: Split Live Hosts
      run: |
        awk '{ print > sprintf("hosts_part_%02d.txt", ((NR-1) % 6) + 1) }' live_hosts.txt
        rm -f nmap_scan_5.txt
        
    - name: Run Nmap scan script on file-5
      run: |
        chmod +x scan_ips_ports.sh
        ./scan_ips_ports.sh hosts_part_05.txt 5

            
    - name: Upload Nmap scan results
      uses: actions/upload-artifact@v4
      with:
        name: nmap_scan_results
        path: nmap_scan_5.txt


  nmap_scan_6:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Install Nmap
      run: sudo apt-get update && sudo apt-get install -y nmap

    - name: Split Live Hosts
      run: |
        awk '{ print > sprintf("hosts_part_%02d.txt", ((NR-1) % 6) + 1) }' live_hosts.txt
        rm -f nmap_scan_6.txt
        
    - name: Run Nmap scan script on file-6
      run: |
        chmod +x scan_ips_ports.sh
        ./scan_ips_ports.sh hosts_part_06.txt 6

            
    - name: Upload Nmap scan results
      uses: actions/upload-artifact@v4
      with:
        name: nmap_scan_results
        path: nmap_scan_6.txt

  collect_all_and_concat:
    runs-on: ubuntu-latest
    steps:

     - name: Download a Build Artifact
       uses: actions/download-artifact@v5.0.0

     - name: Checkout Repo
       uses: actions/checkout@v5.0.0   
  
     - name: Concat files
       run: |
         rm -f nmap_scan_final.txt
         cat nmap_scan_*.txt | uniq -u > nmap_scan_final.txt

     - name: Upload a Build Artifact
       uses: actions/upload-artifact@v4.6.2
       with:
        name: Nmap-scan-final
        path: nmap_scan_final.txt
   






