name: Manual Nmap Scan on IP:Port List

on:
  workflow_dispatch:
    inputs:
      scan_option:
        description: "Single URL or File? (u/f)"
        required: true
        default: 'u'
      target_url:
        description: "Enter Single URL here"
        required: false
      additional_flags:
        description: "Add more flags than service/OS "
        required: false
   
jobs:
  nmap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Install Nmap
      run: sudo apt-get update && sudo apt-get install -y nmap

    - name: Run Nmap scan script on file
      run: |
          option="${{ inputs.scan_option }}"
          flags="${{ inputs.additional_flags }}"
          if [[ "$option" == 'u' ]]; then
            url="${{ inputs.target_url }}"
            echo "Scanning URL"
            clean_url=$(sed -E 's~https?://~~' <<< "$url")
            if [[ -n "$flags" ]]; then
              sudo nmap -sV -O  "$flags" "$clean_url"
            else
              sudo nmap -sV -O "$clean_url"
            fi  
          elif [[ "$option" == 'f' ]]; then
            echo "Scanning file"
            chmod +x scan_ips_ports.sh
            ./scan_ips_ports.sh live_hosts.txt
          fi  

            





